### ISSUE TITLE
Showing video cover element 

### ISSUE THREAD

**Issue by melaniehoff** [lmccart/the-changing-room#113]
bug where the video cover element that is a solid color is not appearing anymore

**Comment by lmccart** [comment]
sorry, i removed this for testing...

**Comment by lmccart** [comment]
fixed with https://github.com/lmccart/the-changing-room/commit/56c97577b0311ae6fd50cdc008a689e504681f84

**Comment by melaniehoff** [comment]
ohhhh i see! got confused because i was having trouble with the cover element last night. sending you an update email now
