### ISSUE TITLE
explore svg filter duotone color of images

### ISSUE THREAD

**Issue by lmccart** [lmccart/the-changing-room#20]
[Here's a link](https://tympanus.net/codrops/2019/02/05/svg-filter-effects-duotone-images-with-fecomponenttransfer/) with some background on this.

[Here's a codepen test.](https://codepen.io/SaraSoueidan/pen/898c0dbac0c8d1f362f8904a7d9fe911) In our case, we could desaturate all the images ahead of time, so only the duotone feColorMatrix would need to be applied. If this is too difficult or creates other problems in the code, we can always batch preprocess images baking in colors, but having it programmatically applied makes it easy to tweak colors on site, which would be nice.

I'll send a batch of desaturated images on Monday.

**Comment by samepant** [comment]
Hey Lauren, 

I took a crack at the svg filter and got a test version working. You can see it in action on the `06-passive` page, and [the functions that does the actual implementation is here](https://github.com/lmccart/the-changing-room/blob/d831a0ff40bd426184a1546b9dfb748c10bf9ff6/areas/js/lib/imageColorUtils.js#L66). Right now, the function takes in a color image, turns it grayscale, applies a slight gamma correction, then maps the image to the color values.

The function takes in the whole color array defined in `colors.json` so the color effect is mapped to how ever many colors are in each array (which is 3 at the moment), which seems to work in some cases, and render the image difficult to see in others. It's pretty nice to switch the emotion and see the effect change.

Another thing to note is the differences in how safari and chrome implement the effect, you can see the difference in this test, where chrome is on top and safari is on the bottom:
![Screen Shot 2020-12-11 at 2 55 12 PM](https://user-images.githubusercontent.com/6718506/101963598-15885700-3bdd-11eb-9e8b-71fa977c05d7.png)

**Comment by lmccart** [comment]
@samepant this looks great! I was planning to use chrome so I'm glad to see that one is looking better. I think we'll just do a 2-color mapping instead of 3, so that should make things more readable. We can select two colors that are high contrast enough that it should feel readable for most images. I'm planning to update the colors.json file so each emotion is actually 2D array of 3 elements, each element representing the 2 hex pair for that level of emotion. If that wasn't clear, I'll update the colors.json file this weekend and it should make sense then. Anyway, glad to see this works! It really opens things up for install.
