### ISSUE TITLE
intro text should pull from `data/00_intro.txt`

### ISSUE THREAD

**Issue by lmccart** [lmccart/the-changing-room#27]
Currently displays some very wonderful placeholder text. :)

Section should be ready for sign-off once this is updated. Maybe we mark that by adding a "APPROVED" card to the "Done" column for this project?
Time permitting, we could do one final round of review/tweaks once all sections are APPROVED.

**Comment by melaniehoff** [comment]
@lmccart adding an APPROVED card to the projects page sounds good! 

[Intro Projects page](https://github.com/lmccart/the-changing-room/projects/1)
