### ISSUE TITLE
03-selection design tweaks

### ISSUE THREAD

**Issue by lmccart** [lmccart/the-changing-room#29]
* Add color gradient to background.
* Increase size of 4 column text so longest word fills full width of column.

<img width="1047" alt="Screen Shot 2020-12-12 at 4 00 40 PM" src="https://user-images.githubusercontent.com/191056/101999575-52168a00-3c93-11eb-9c62-93671cb49a73.png">

**Comment by lmccart** [comment]
Hi @ammeitzler here's a more specified flow for the emotion selection area. Note that we had to switch to 3 larger monitors because the ones we wanted to use were unavailable. It looks like for the emotion selection part, this flow is pretty much there, we just need a longer delay before going to idle mode. Let me know if you have any questions! 
[emotion-selection.pdf](https://github.com/lmccart/the-changing-room/files/5738170/emotion-selection.pdf)



Here's a temp pointer png file you can use (it's white so it's not really showing up in the preview).
![pointer](https://user-images.githubusercontent.com/191056/103048599-0215ae00-4544-11eb-8804-6a5e0352160a.png)

**Comment by ammeitzler** [comment]
this room is ready for feedback! but still gotta fix the jumpy text in idle mode @lmccart

**Comment by lmccart** [comment]
@ammeitzler looks great! I just submitted PR #61 with a few style tweaks. 
a few notes, and then this one is DONE:
* can we add a scrollbar similar to 00-intro area?
* text scrolling isn't quite working in idle mode (I think that's what you're referencing in your comment)
* it seemed like scroll to center emotion name sometimes didn't work in emotion selection mode? but usually it did, maybe I was just testing wrong.

**Comment by ammeitzler** [comment]
yay :) 
- added the scrollbar from 00-intro area
- fixed text scrolling in idle mode

(i think im seeing the issue with the scroll to center emotion name. will fix!)
