### ISSUE TITLE
05-convo2 final changes

### ISSUE THREAD

**Issue by lmccart** [lmccart/the-changing-room#30]
This section looks great! I see a "set up dynamic image background" card in General, which is the only thing missing here, so I think this area can be marked APPROVED.

**Comment by lmccart** [comment]
I'm updating this issue to include a few last things I noticed. Once these are resolved, this section is APPROVED.

* Strange behavior on emotion change. It looks like previous directions are not being stopped, and two different ones are spelling out simultaneously.
<img width="2048" alt="Screen Shot 2021-01-04 at 1 22 06 PM" src="https://user-images.githubusercontent.com/191056/103581163-55ff8b80-4e90-11eb-9255-7d7f6ce3dbc8.png">

* Missing loading transition. Sorry, I think the wireframes weren't clear enough. Every area should have a similar loading transition sequence (Screen blurs out. White text “Loading... [EMOTION]” appears. “...” animating 1, 2, 3 dots. Background image switches. Loading text disappears and screen unblurs.)
<img width="1611" alt="Screen Shot 2021-01-04 at 1 26 33 PM" src="https://user-images.githubusercontent.com/191056/103581268-8c3d0b00-4e90-11eb-86a4-855e4df7fcf4.png">

* Missing rotating background image. Image rotates on each new instruction load, right as "Next instruction coming..." changes to typing out the prompt.

**Comment by samepant** [comment]
Got some fixes in for these in this pr https://github.com/lmccart/the-changing-room/pull/72 :)
