### ISSUE TITLE
02-reflection spec

### ISSUE THREAD

**Issue by lmccart** [lmccart/the-changing-room#31]
Hi all, here's some clearer direction for the reflection room.

<img width="692" alt="reflection" src="https://user-images.githubusercontent.com/191056/102019448-812b0b00-3d28-11eb-80cc-0f6ce577f120.png">

**Content:** Meditative, reflective space. Text and audio. Begins with directed meditation via spoken computer voice. Partway through, eases into memory space, with snippets of text and photos.

**Tech:** 3x 1080p projection. Isadora to spread single browser window over three wall projection. Note: Left and right projection walls may not have width for full 1920. I'll find out the exact dimensions this week.

**Visual:** There are two sections, that flow from the first (guided meditation) to the second (memory space). 

During meditation section:
* Text from `/data/02_meditation.txt` spells out, one phrase every 3 seconds. 
* [BRACKETED TEXT] is replaced by data from `/data/02_meditation_emotion_specific.tsv`. 
* Background is one image, mirrored on left and right to create continuous image. 
* After final phrase, text and box outline pop out. Background stays.

<img width="692" alt="reflection copy" src="https://user-images.githubusercontent.com/191056/102019482-b172a980-3d28-11eb-803a-f5379a53f688.png">

During memory section:
* Windows popup revealing fragments of text and image. Tempo of popups may vary based on level of emotion. Background images rotate every 10s with crossfade. 
* Note: Image above isn't quite accurate because the popover images are blue and the background is purple. I realize it won't work to lay the exact same colored images over background, but we might experiment with two different svgcolor functions. Maybe one uses the current emotion level, and the background uses the coloring from a different emotion level. Or something like this.
* Entire section lasts 120s. Then windows popout leaving only background for 5s. Then meditation begins again.

**Comment by dantaeyoung** [comment]
Hi @lmccart - You mention "Begins with directed meditation via spoken computer voice." - is this text-to-speech or pre-recorded? And if it's TTS, do you have any specific voices/libraries you'd prefer or should I just pick one?

**Comment by lmccart** [comment]
Ah! It will be prerecorded and baked into the audio tracks, so no TTS needed. You can ignore this part completely in terms of the software dev.

**Comment by dantaeyoung** [comment]
Ah okay! And are the audio tracks synced to each phrase from `/data/02_meditation.txt` (each 3 seconds long audio files) and triggered on each new phrase, are the audio tracks longer and decoupled to the phrase animations?

**Comment by lmccart** [comment]
It will be one long audio file that will be laid over the normal sound for each emotion. But my thought was to space out each phrase within that audio so it can be on a predictable interval for the text display. Maybe this should be every 5 or 10s to ensure there's enough time for the phrase to complete and there to be a pause. I can do some tests this week and send you a sample audio file.

**Comment by dantaeyoung** [comment]
That sounds good. 

Just did some research and found an option that's simple development-wise but more labor for you: to use `howler.js` and [audio sprites](https://github.com/goldfire/howler.js#define-and-play-a-sound-sprite). [Example](https://howlerjs.com/#sprite)

If the prerecorded audio file has the predictable interval you mention, and you can get the millisecond timings for each phrase, then the audio can be pretty easily timed to each specific phrase & the timing could be adjusted easily in code. 

The only downside I can see (other than the added labor) is that any changes in audio background noise (or its absence) would be audible when moving between phrases. What do you think?

**Comment by lmccart** [comment]
The way their Sonos sound system is setup, I have to premake all audio tracks. So what I'm imagining is that this area will have a special set of tracks, that have the entire spoken text baked in. It will sync with the screens by having a predictable schedule (a phrase every 10s then no speaking for 120s, or similar). The entire track will start and loop at the same time the software is looping keeping it roughly in sync. Does that seem workable?

The other way would be to try a streaming to Sonos solution and triggering the audio via software. But this adds another layer of stuff, so if the timing seems close enough with the previous solution I'd like to stick with that.

If the timing is slightly off, I was thinking one solution is to have the displayed text be excerpts from the audio, rather than word for word the same. That way you don't feel the out of syncness.

Assuming we're good with the prebake Sonos sound solution, you won't need to worry about programming sound into the software at all, I'll handle that with my sound.js module. We'll just need to check in on timing to make sure we're in sync. I can confirm timing and send some sample audio files by Tuesday for you to try out.

**Comment by lmccart** [comment]
Here are a couple audio samples. Right now there's 5 seconds before the first spoken direction, 5 seconds between directions, and the total length is 2 minutes.
[Archive.zip](https://github.com/lmccart/the-changing-room/files/5737601/Archive.zip)

**Comment by dantaeyoung** [comment]
Hi @lmccart! I just tested out the audio timing by creating a 3000ms delay between text and accounting for each spoken word as lasting 250ms. It's okay, and works surprisingly well.. but it's not _perfect_. It's in #79 - could you take a look?

re: the prebaked audio loops: While that does make sense, wouldn't this have to account for emotion changes and the narrative / sound being interrupted/restarted upon emotion selection?

**Comment by lmccart** [comment]
hey @dantaeyoung I left the comment on timing over on https://github.com/lmccart/the-changing-room/pull/79.

regarding the interruption, this is a good point. I was originally thinking it would just restart with emotion change but this could be very disruptive. could we instead hold any emotion change message until the start of the meditation section?

if this is too tricky to implement, we could just ignore all change messages that come during the meditation part (still allowing changes during memories part), and then always do a check for current emotion on meditation restart in case a change got missed.

**Comment by dantaeyoung** [comment]
> could we instead hold any emotion change message until the start of the meditation section?

Sounds good - so just to be clear, do you mean:

1. Reflection room is going as is with the emotion (e.g. `joyful`)
2.  Someone changes the emotion to `carefree`
3.  Reflection room continues as planned with the same `joyful` emotion / image sequence, not visibly registering any difference
4.  Upon completion and loop back to meditation section, THEN the emotion changes to `carefree` (assuming that no other emotion change messages were received)
5.  Reflection room proceeds as `carefree`

?

**Comment by lmccart** [comment]
Correct!

This brings up the question of loading screen. Ideally, if the emotion has changed (Reflection room proceeds with `carefree`) the loading screen appears at this point so the view knowers. It would show for a few seconds, **without delaying** the playing of content so the audio stays synced. It would just be a layer + blur on top of what's playing, that then disappears. Does that seem possible?

**Comment by dantaeyoung** [comment]
Ah got it -  that's totally possible, yes. So it's 

1. Reflection room is going as is with the emotion (e.g. joyful)
2.  Someone changes the emotion to carefree
3.   Reflection room continues as planned with the same joyful emotion / image sequence, **but a loading screen appears on the screen (blurring the background) for a few seconds, then disappears.**
4.  Upon completion and loop back to meditation section, THEN the emotion changes to carefree (assuming that no other emotion change messages were received)
5. Reflection room proceeds as carefree

**Comment by lmccart** [comment]
I think we'd want to do the loading screen at the moment when the change is actually reflected, so it would be:


1. Reflection room is going as is with the emotion (e.g. joyful)
2.  Someone changes the emotion to carefree
3.   Reflection room continues as planned with the same joyful emotion / image sequence.
4.  Upon completion and loop back to meditation section, THEN the emotion changes to carefree (assuming that no other emotion change messages were received). **A loading screen appears on the screen (blurring the background) for a few seconds, then disappears. Content continues with normal timing behind it.**
5. Reflection room proceeds as carefree

**Comment by dantaeyoung** [comment]
Ah okay got it - sounds good!

**Comment by lmccart** [comment]
Hi @dantaeyoung following up on this area after the tech test. Since it looks like they won't be able to do a single surface projection, I'd like to move to this area as three separate browser tabs, each fullscreen and sent to projector output. The three different tabs could have address:
```
http://localhost:3000/02-reflection?screen=0
http://localhost:3000/02-reflection?screen=1
http://localhost:3000/02-reflection?screen=2
```

The design would stay mostly the same (with the white borders and image reflection as planned. However, the text should go only on the middle screen, and the popups should be positioned so they're fully within their own tab view. There will be some slight async with the different tabs, but I think it's preferable and easier than mirroring all three sides the same somehow.

I guess I would start by working with the current code as if it's a single projection (1769 x 1080px). Then modifying so it takes the param and updates the overall dimensions, position of the border, background div, and hides the meditation text as needed. Here are the three preliminary pixel dimensions. We'll want to be sure these are held in variables where we can update easily, including the height.

```
LEFT (screen=0) 1631 x 1080
CENTER (screen=1) 1768 x 1080
RIGHT (screen=2) 1700 x 1080
```

Does that all make sense?

**Comment by dantaeyoung** [comment]
Hi @lmccart - this makes sense! 
- screen 0:  memory image popups only
- screen 1: meditation text & memory text popups
- screen 2: memory image popups only
Is this correct?
Re: async; I can try to round the timing to the nearest second so that if the computer's clocks are all synced on time, the timing could be as synchronized as possible

**Comment by lmccart** [comment]
perfect!

**Comment by lmccart** [comment]
and loading screen visible on all three

**Comment by dantaeyoung** [comment]
Hi @lmccart  - I'm closing this comment and splitting it into #96 and #95 (just so it's easier for me keep track); let me know if you catch anything that's missing.
