### ISSUE TITLE
intro scroll issue

### ISSUE THREAD

**Issue by lmccart** [lmccart/the-changing-room#55]
Intro scroll seems to stop before it gets to the end. Sometimes it scrolls back up to the top, other times it just hangs there. Here's a screenshot from a time when it hung.
<img width="1994" alt="Screen Shot 2020-12-27 at 10 38 37 PM" src="https://user-images.githubusercontent.com/191056/103194409-6dd57f00-4894-11eb-864e-aff19675104a.png">

**Comment by melaniehoff** [comment]
https://github.com/lmccart/the-changing-room/pull/67
