### ISSUE TITLE
Wishlist - round Timeline.js syncing to nearest second to better synchronize 02-reflection across screens

### ISSUE THREAD

**Issue by dantaeyoung** [lmccart/the-changing-room#96]

**Comment by dantaeyoung** [comment]
@lmccart Since it looks like the synchronizing across screens is no longer triggered upon emotion change (as we talked about here: https://github.com/lmccart/the-changing-room/issues/31#issuecomment-758232556), the separate tabs sync is really dependant on quickly refreshing the browsers at nearly the same time. I can imagine this being an issue if one of the computers has to be restarted.

How do you want to handle this? Maybe the server could send a special `meditation_sound_starting` message that could be used to trigger the reflection room start?

**Comment by lmccart** [comment]
Hm good question. We had talked about a message that gets sent back to the server on restart, to sync the audio. Could the middle screen be the driver? So the flow is:

- Sequence is playing through, it gets to the end of popups.
- Middle screen emits an "end" message to the server.
- Server restarts audio. Emits a "restart" message back to clients, including the current emotion with it.
- All 02-reflection tabs receive message and restart.

**Comment by dantaeyoung** [comment]
Hi @lmccart  - I left a comment (https://github.com/lmccart/the-changing-room/pull/109#discussion_r565830729) - I resolved this in #109 but left the audio aspect to you.

**Comment by dantaeyoung** [comment]
Hi @lmccart  - I left a comment (https://github.com/lmccart/the-changing-room/pull/109#discussion_r565830729) - I resolved this in #109 but left the audio aspect to you in `server.js` because I think you were handling that? Happy to take a look if you'd like.

**Comment by lmccart** [comment]
Thanks @dantaeyoung! I'll figure out the audio part.
