### ISSUE TITLE
02-Reflection background should have more accurate colors

### ISSUE THREAD

**Issue by dantaeyoung** [lmccart/the-changing-room#99]
More accurate color should be used. 

From #31: 

> Note: Image above isn't quite accurate because the popover images are blue and the background is purple. I realize it won't work to lay the exact same colored images over background, but we might experiment with two different svgcolor functions. Maybe one uses the current emotion level, and the background uses the coloring from a different emotion level. Or something like this.

**Comment by dantaeyoung** [comment]
@lmccart Sorry if I'm missing something, did you have any updated specs on how you wanted the emotion colors to apply onto the background / memory / meditation colors?

**Comment by lmccart** [comment]
Could we try something like this (shifting off by one from current level). 
https://github.com/lmccart/the-changing-room/blob/main/areas/js/06-passive.js#L111

**Comment by dantaeyoung** [comment]
Partially resolved via 44e1e11, images still need to be colored.
